error: dto does not exist
when compiling, target folder doesn't have dto.
is it can make sense?

solution: add "	implementation fileTree(dir: 'lib', include: ['*.jar'])" in dependency.